version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/byteload-agent
    binary: byteload-agent
    ldflags:
      - -s -w -X main.version={{.Version}}

nfpms:
  - vendor: Byteload
    homepage: https://github.com/yourusername/metrics-agent-go
    maintainer: Your Name <your.email@example.com>
    description: Byteload Metrics Agent
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      - src: configs/byteload.yaml
        dst: /etc/byteload/byteload.yaml
        type: config|noreplace
      - src: deploy/env.sample
        dst: /etc/byteload/env
        type: config|noreplace
      - src: deploy/byteload.service
        dst: /lib/systemd/system/byteload.service
    scripts:
      postinstall: ./deploy/scripts/postinstall.sh
      postremove: ./deploy/scripts/postremove.sh

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - configs/*
      - deploy/*
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:' 